{% set name = "flake8-isort" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81e8c2ff17e8cf267b82bf46e3f404433017bf25f24d3f3554d67586d6af95da

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - flake8 >=3.2.1
    - isort >=4.3.0
    - python
    - testfixtures

test:
  imports:
    - flake8_isort

about:
  home: https://github.com/gforcada/flake8-isort
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: flake8 plugin that integrates isort .
  dev_url: https://github.com/gforcada/flake8-isort

extra:
  recipe-maintainers:
    - marcelotrevisani
