{% set name = "flake8-isort" %}
{% set version = "6.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9d0452acdf0e1cd6f2d6848e3605e66b54d920e73471fb4744eef0f93df62d5d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - flake8
    - isort >=5.0.0,<7

test:
  imports:
    - flake8_isort
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/gforcada/flake8-isort
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: flake8 plugin that integrates isort .
  dev_url: https://github.com/gforcada/flake8-isort

extra:
  recipe-maintainers:
    - dopplershift
    - marcelotrevisani
    - xylar
