{% set name = "flake8-isort" %}
{% set version = "6.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c1f82f3cf06a80c13e1d09bfae460e9666255d5c780b859f19f8318d420370b3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - flake8
    - isort >=5.0.0,<6

test:
  imports:
    - flake8_isort
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/gforcada/flake8-isort
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: flake8 plugin that integrates isort .
  dev_url: https://github.com/gforcada/flake8-isort

extra:
  recipe-maintainers:
    - dopplershift
    - marcelotrevisani
    - xylar
